version: '3'
services:
  redis:
    # container_name: redis
    hostname: redis
    image: redis
    ports:
      - "8006:6379"

  redis-commander:
    depends_on:
      - redis
    # container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8005:8081"

  twitter-metrics:
    depends_on:
      - redis
    build: ./project/twitter-metrics
    environment:
      - REDIS_HOSTS=local:redis:6379
      - "TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}"