version: '3'

volumes:
  redis:

services:
  redis:
    # container_name: redis
    restart: always
    hostname: redis
    image: redis
    # command: bash -c "redis-server --appendonly yes --requirepass <password>"
    command: bash -c "redis-server --appendonly yes"
    ports:
      - "8006:6379"
    volumes:
      - redis:/data

  redis-commander:
    restart: always
    depends_on:
      - redis
    # container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8005:8081"

  twitter-metrics:
    restart: always
    depends_on:
      - redis
    build: ./project/twitter-metrics
    environment:
      - REDIS_HOSTS=local:redis:6379
      - "TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}"

  api:
    depends_on:
      - redis
    build: ./project/api
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8002:8002"

  ui:
    depends_on:
      - api
    build: ./project/ui
    environment:
      - API_HOST=http://api:8002
    ports:
      - "8000:80"
